{
  "language": "node_js",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "sudo": false,
  "node_js": [
    "14",
    "13",
    "12",
    "11",
    "10",
    "9"
  ],
  "install": [
    "cd server && npm install"
  ]
}