name: famtrack
description: A tracker app to implement geo-fencing for your family members.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.0.4
  flutter_map: any
  geolocator: ^6.1.13
  latlong: ^0.6.1
  flutter_dotenv: ^2.1.0
  http: ^0.12.2
  url_launcher: ^5.7.0
  shared_preferences: ^0.5.12+4
  image_picker: ^0.6.7+14
  image_cropper: ^1.3.1
  email_validator: ^1.0.5
  share: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/family_splash.png"
  image_path_android: "assets/images/family_splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 700

